### PR TITLE
OA-532: Convert the email alerts to HTML

### PR DESCRIPTION
**Pull request by henare**
This is the start of [OA-532](https://tickets.openaustraliafoundation.org.au/browse/OA-532) by @mattjoyce 

To do:
- [ ] Rebase/merge master
- [ ] Deploy to staging to test
- [ ] Style HTML emails

### CODE REVIEW

**Comment by mattjoyce** [comment]
So, shall I close this pull request and issue another, when it's ready?

**Comment by davidjeliba** [comment]
I thought this issue was the conversion from plain text to HTML emails using the template from openaustralia/twfy#8

I believe this is the issue for implementing the template across the different email types that are sent from the system.

**Comment by mattjoyce** [comment]
Well, it was the first attempt, I have a more complete solution, using your
template.
I'm committing it to a branch in my fork, and then I'll request a new pull.

I think that the right approach, but happy to be advised.


On Thu, Feb 5, 2015 at 9:29 PM, davidjeliba <notifications@github.com>
wrote:

> I thought this issue was the conversion from plain text to HTML emails
> using the template from openaustralia/twfy#8
> <https://github.com/openaustralia/twfy/pull/8>
>
> I believe this is the issue for implementing the template across the
> different email types that are sent from the system.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaustralia/twfy/pull/4#issuecomment-73025202>.
>



-- 
+61 468 335597
*LinkedIn Profile : Matt Joyce
<http://au.linkedin.com/pub/matthew-joyce/6/4b5/6a4/>*

**Comment by davidjeliba** [comment]
I think the new pull request would work well then.

**Comment by mattjoyce** [comment]
I'm closing this pull request, and have request an alternate, which has all these commits too.

**Comment by mattjoyce** [comment]
Nope, I think both will be needed.  Reopened.

**Comment by henare** [comment]
I'm closing this so we can start fresh.

I'll then merge #10 into the `OA-523` branch and open a new pull request that contains everything.

**Pull request closed without merging**
