### PR TITLE
[Demographic survey

### PR DESCRIPTION
**Pull request by equivalentideas**
This adds the code to ask 30% of people who visit the site to answer a few questions for us so we can learn more about who they are and how they use the site.

The survey is hosted by mySociety and they will compare the results to data collected on other similar sites from around the world.

### CODE REVIEW

**Comment by equivalentideas** [comment]
@henare could you please review this for me.

**Comment by henare** [comment]
@equivalentideas looks OK to me. Do you want this merged and deployed?

**Comment by equivalentideas** [comment]
@henare Thanks for that. Let's hold on the merge and deploy, I've got some questions out to @jacksonj04 in an email about changing the content of the survey.

**Comment by equivalentideas** [comment]
@henare could you merge and deploy this please.

**Pull request merged**
