### PR TITLE
[For Review] Mysociety experiment changes

### PR DESCRIPTION
**Pull request by equivalentideas**
These changes add the page, links, modal and scripts required for the mySociety experiment. I've tried to match this as closely to the experience on TheyWorkForYou, but in the style of OpenAustralia.org.au.

Closes https://github.com/openaustralia/openaustralia/issues/572

One MP and speech pages users assigned to bucket 1 or 2 by the quant2.js script.

**Bucket 1** users will have a modal appear on the page after ten seconds:

screen shot 2015-06-04 at 11 48 38 am
screen shot 2015-06-04 at 11 50 36 am

**Bucket 2** users will see a link in the sidebar 'What to do with the information on this page?':

screen shot 2015-06-04 at 11 53 56 am
screen shot 2015-06-04 at 11 53 39 am

The placement on speech pages bumps the layout a bit on load (as the TheyWorkForYou version does), but this is the best position I could manage in our layout system.

For users on phones this is at the bottom of the page:

screen shot 2015-06-04 at 11 52 29 am

The 'Where's next' page is consistent with the site styles:

screen shot 2015-06-04 at 12 01 58 pm

## Testing locally

I am running the app in Kitematic on OSX, following these steps:

### 1. Download docker containers

In [Kitemaic](https://kitematic.com/) add the containers [leowmjw/oa-ubuntu-trusty-db](https://registry.hub.docker.com/u/leowmjw/oa-ubuntu-trusty-db/) and [leowmjw/oa-ubuntu-10.04-web/](https://registry.hub.docker.com/u/leowmjw/oa-ubuntu-10.04-web/) (Thanks @leowmjw). This could take a while depending on your connection speed.

### 2. Get the containers running

Open the Kitematic docker terminal and run `docker run -d -i -t -p 3306:3306 leowmjw/oa-ubuntu-trusty-db:latest` to start the database container.

Then run `docker run -d -i -t -p 80:80 -v <location of your openaustralia repo>/openaustralia/twfy/www/:/var/www/openaustralia/twfy/www/ leowmjw/oa-ubuntu-10.04-web /run.sh` replacing "<location of your openaustralia repo>" with your local directory. This starts the web server container using the `-v` option to load your local `/twfy/www` folder for the web application content. 

Kitematic may assign it's own names for these running containers for some reason, mine uses 'boring torvolds' and 'trusting morse'.

### 3. Adjust the server and application config for Kitematic

@leowmjw's containers weren't set up for use with Kitematic, so there are two changes to make to make to run properly. Select the running container 'oa-ubuntu-10.04-web' in Kitematic and open its terminal using the button below the container title.

Firstly, change the apache config to match the root url used by Kitematic:

1. Navigate to `/etc/apache2/sites-enabled/`
2. Open the file `httpd.conf.ubuntu`
3. Change line 9 to `ServerName 192.168.99.100.xip.io`
4. Save and exit the file
5. Restart the apache2 server with `service apache2 restart`

If you open http://192.168.99.100.xip.io/ in your browser, you should see an error 'Can't connect to MySQL server on '192.168.111.6...'. Fix the database connection:

1. Navigate to `/var/www/openaustralia/twfy/conf`
2. Open the file `general`
3. Change the value for DB_HOST on line 7 to: `192.168.99.100:3306` to address and port for the database container.
4. Save and exit the file and check that the application is working as expected at http://192.168.99.100.xip.io/

You can change the bucket assigned to you by the script in the browser console with:

```
  researchUser = {
    'bucket': 2,
  };
  $.localStorage.set('research.qual2', researchUser);
  $.localStorage.set('research.qual2.suppress_popup', false);
```

@jacksonj04 have you been successfully receiving data as I've been running the scripts in developing this? Is there any testing we need to do with you before deploying?

I would like to also get the 'Wherenext' page to use the mobile theme, and to set up GA tracking on those links, but this PR is not dependent on that as it doesn't not impact the experiment.

### CODE REVIEW

**Comment by henare** [comment]
@equivalentideas I've reviewed the code and I'm amazed you've done such a nice job on your first encounter with this very "unique" codebase - great work! :tada: 

>@jacksonj04 have you been successfully receiving data as I've been running the scripts in developing this? Is there any testing we need to do with you before deploying?

This is ready to deploy once @jacksonj04 gets back to us. I can also deploy to staging if that would help.

**Comment by jacksonj04** [comment]
@equivalentideas It all looks good to me, and I can confirm we're receiving data at our end! :+1:

One tiny thing, we don't seem to have had any test data for bucket 3. This is probably just that you haven't actually tested bucket 3 because it's the boring one, but just so you're aware if you think we *should* have data for it.

**Comment by equivalentideas** [comment]
Thanks for that @jacksonj04 you're right, I have tested bucket three. I'm gonna just test that works as expected and if it's all good we'll move to deploy this.

**Comment by equivalentideas** [comment]
@jacksonj04 I've done some clicking about while in bucket three—it's not showing me the link or popping up the modal so that's working correctly as I understand it. I'm actually a bit unclear to the purpose of bucket 3.

So, I'm going to assign this back to @henare for deployment.

**Comment by henare** [comment]
Deployed :rocket: and briefly tested it works for me.

**Comment by jacksonj04** [comment]
Bucket 3 is just so we can get hard data on how many people were in the control group, it's not actually doing anything clever.

Just to let you know we're receiving data from production as expected.

Yay!

**Comment by equivalentideas** [comment]
Nice :) Thanks @jacksonj04

**Pull request merged**
